'use strict';

var quotes = [
    'Willie, ich möche mit dir über meinen letzten Willen sprechen ... sprechen wir mal über die ewige Ruhe. Ich stell mir eine Pyramide vor ... nichts grosses ...',
    'Deine Augenlieder werden schwer. Du wirst ganz müde. Deine Pfoten schlafen ein. Du bist jetzt keine Katze mehr, Du bist ein Krapfen.',
    'Null Problemo!',
    'Sag mir Deine Meinung, und ich sage Dir, wer für dich denkt.',
    'Hallo ist da die Auskunft? Geben sie mir Brians Lehrerin ... Achso, ja. Dann verbinden sie mich mit der Franklin Elementar Schule ... Ja, ich weiss, dass es über das Telefonbuch billiger geht, aber ich habe leider nur drei Finger und \'n Daumen ... Ja, das sollte ihnen auch leid tun ...',
    'Ich hab nicht eingebrochen. Ich habe ein Stemmeisen benutzt.',
    'Etwas nicht tun zu können, heisst noch lange nicht, es nicht zu tun.',
    'Glaubst du, du kannst mich mit einem Eis rumkriegen...? Bitte ja ... aber nur mit Rumtraube-Nuss!',
    'Essen wir erst einen Happen ! Wie wärs mit einer Dose Katzenfutter? Ich brauche Ballaststoffe!',
    'Wozu ich den Wäschetrockner nachts laufen lasse? Ich brauche ein bisschen Gesellschafft! Sind acht Stunden zu lang?',
    'Übrigens, der Staubsauger ist kaputt! Die Generalvertretung meint, sie kriegen den Geflügelsalat nicht mehr raus und müssen ihn zur Generalüberholung nach Japan schicken!',
    'oh ... ich sollte vor dem schlafengehen keine Filme mehr essen ...',
    'Merk dir, bring deiner Freundin immer was mit! Eine Blume, etwas Konfekt, oder einer Rambo-Puppe!',
    'Die Staatsbibliothek auf Melmac hatte zwei Bücher, als sie abbrannte. Und eines war noch nicht mal ausgemalt.',
    'Du bist ganz schön gewitzt fuer einen ohne Fell!',
    'Ich und arbeiten? Arbeiten ist was für Ackergäule aber nicht die Aufgabe eines Topmanagers!',
    'Wenn du mich brauchst, ich bin im Kühlschrank.',
    'Das beste Mittel gegen eine gegessene Schokolade ist eine neue Schokolade.',
    'Oma Shumway pflegte immer zu sagen: Schau niemals zurück, du ersparst dir den Blick ins Chaos.',
    'Entschuldigung! Hast du gesagt, ich soll aufpassen, dass Haare in die Erdnussbutter reinkommen, oder nicht?',
    'Schnecken - eine Bedrohung für alle von uns, die barfuß gehen.',
    'Wer kriecht kann nicht stolpern.',
    'Wenn ich mehr Zeit hätte, würde ich zwei Armbanduhren tragen!',
    'Der Wagen schnurrt wie eine Katze! Da fällt mir ein, ich habe Hunger!',
    'Das Geheimnis beim Bowling - oder Tallaquoids, wie es im zivilisierten Universum genannt wird - liegt im Reifegrad der Melone.',
    'Und du hast Gold? Ich hatte Gold, alle Leitungen in meinem Raumschiff waren aus Gold! Nur die Toilette nicht - díe war nämlich aus Platin!',
    'Es nie zu früh und selten zu spät.',
    'Hey! Null Problemo! Laßt mir nur den Schlüssel zum Schnapsschränkchen da!',
    'Keine Panik, ich weiß durchaus nicht, was zu tun ist.',
    'Sag mal Willie, würde eine Pizza nicht gut zu meiner Zunge passen, ich meine auf farblich?',
    'Wie mein Glitschballtrainer immer zu sagen pflegte, versuche rauszufinden was du nicht gut kannst,und dann lass es bleiben.',
    'Es regnet KATZEN? - Mach die Dachfenster auf, ich hol schonmal die Mayonnaise!!!',
    'Traditionen sind wie Teller: Gemacht, um in Stück zu fallen!',
    'Ich will allein sein. Komm Brian, leiste mir dabei Gesellschaft.',
    'Tut nichts, was ich nicht auch tun würde!',
    'Ich weiss, wie man sowas dezent behandelt. Äh, wo haben wir die Scheinwerfer und die Lautsprecher?',
    'Meine Herren vom Außerirdischen Einsatzkommando. Retten sie mein Leben und ich biete ihnen dafür ein ungeheures technisches Geheimwissen. z.B. wie programmiere ich einen Videorecorder...',
    'Keine Sorge, meine bezaubernde Assistentin wird das gleich wegräumen.',
    'Mir fällt auf, dass du einen Haufen Zeit mit Reparaturen verbringst, Willie.',
    'Das ist kein Essen, das verfüttert man an das Essen!',
];
